name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'be-koptel-keuangan/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: cd be-koptel-keuangan && npm install

      - name: Run Tests
        run: cd be-koptel-keuangan && npm test --if-present
